### ISSUE TITLE
Improve css

### ISSUE THREAD

**Issue by AkashDev23** [AkashDev23/portfolio#1]
Navbar is good. try to make the website as shown in the design. I've commented all the lines. Edit them. Delete the icons of socials from the project folder and use the icons from font awesome.

**Comment by maheshwar04** [comment]
assign this to me

**Comment by AkashDev23** [comment]
sure...

**Comment by AkashDev23** [comment]
Change the font of front div. Also change the hover effect of the contact button. It's not looking good
